[package]
name = "neon_solitaire"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
opt-level = 3
lto = true